apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: greeting
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - greeting.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: greeting
spec:
  hosts:
  - greeting.com
  gateways:
  - greeting
  http:
  - match:
    - uri:
        prefix: /
    fault:
      delay:
        percent: 100
        fixedDelay: 5s
    route:
    - destination:
        host: greeting.default.svc.cluster.local
        port:
          number: 8080
