apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: greeting
spec:
  hosts:
  - greeting
  http:
  - fault:
      delay:
        percent: 100
        fixedDelay: 10s
    route:
    - destination:
        host: greeting
        subset: greeting-hello
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: greeting
spec:
  host: greeting
  subsets:
  - name: greeting-hello
    labels:
      app: greeting
