apiVersion: v1
kind: Service
metadata:
  name: skaffold-greeting-service
spec:
  selector:
    app: greeting
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
