apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-name
  labels:
    name: {{ .Release.Name }}-name
    {{- template "labels" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-name
    spec:
      containers:
      - name: name
        image: {{ .Values.name.image }}:{{ .Values.docker.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /resources/names/1
            port: 8082
          initialDelaySeconds: 50
          periodSeconds: 5
        env:
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: xray-service.default:2000
