apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-name
  labels:
    name: {{ .Release.Name }}-name
    {{- template "labels" . }}
spec:
  selector:
    app: {{ .Release.Name }}-name
  ports:
  - name: http
    protocol: TCP
    port: 8082
